### ISSUE TITLE
appsmith template import error

### ISSUE THREAD

**Issue by ja1sh** [PhonePe/mantis#7]
Getting the following error while using the Mantis Dashboard.json file with AppSmith import.
`
Error: Unable to import artifact in workspace 65f5fc6e63ea80239fe4ae89. Error: Command failed with error 112 (WriteConflict): 'WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.' on server localhost:27017. The full response is {"errorLabels": ["TransientTransactionError"], "ok": 0.0, "errmsg": "WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.", "code": 112, "codeName": "WriteConflict", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1710661300, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "lB1/RuBLp09NysJEF+SsGLgzhj8=", "subType": "00"}}, "keyId": 7347054636601180165}}, "operationTime": {"$timestamp": {"t": 1710661300, "i": 1}}}
`

**Comment by Prateek-Thakare** [comment]
Hi @ja1sh 
Thanks for raising this issue, we will check this on our end. Thanks for your patience.

**Comment by llwp** [comment]
This may be a related issue, or it may be different.  It seems related to me, but lmk if a new issue is preferred.

New to AppSmith, and so the UI / setup process needed a bit more for me in Setup, but I can put in PRs for improvements once this is resolved.

In the AppSmith UI, under `my-first-application/page1` (default naming convention) which is the Page1 UI element in the upper left where the 3 dots permit the Page Import operation (specifically, "Import partial application from file"): using the "Mantis Dashboard.json" file for import results in a pop-up error with the message "Unable to import artifact in workspace The file is not compatible with the current partial import operation. Please check the file and try again.. {1}" as seen here:

![Screenshot 2024-04-05 114806](https://github.com/PhonePe/mantis/assets/9566542/9eaa5a09-95ad-40a2-9dc1-2ed284238288)

(1) what is being done incorrectly here
(2) or is there a file/format issue - perhaps due to AppSmith updates

I found other place(s) to import (and tried them) but no joy.  Also, I did connect the MongoDB datasource successfully.

tia!

**Comment by Prateek-Thakare** [comment]
Hey @ja1sh 
Can you check if you are importing the template from the main home page of appsmith under the create new option?

**Comment by ja1sh** [comment]
@Prateek-Thakare 
Yes, I am getting the same error.

**Comment by Ncoder2** [comment]
Hi @ja1sh , can you retry this with the  steps from the documentation here :
https://github.com/PhonePe/mantis?tab=readme-ov-file#dashboard-setup-

**Comment by Ncoder2** [comment]
Hi @ja1sh , since there is no response, am closing this issue. Please try to replicate the steps mentioned in the above link. If it still does not work, please re-open the issue later

**Comment by Ncoder2** [comment]
Hi @ja1sh , since there is no response, am closing this issue. Please try to replicate the steps mentioned in the above link. If it still does not work, please re-open the issue later
